export { Engine, buildPresetContext } from "./engine";
export { evaluateCondition } from "./condition";
export { choiceDecisionContext, resolveChoiceInput } from "./decision";
export { classifyInput, expectedInputs } from "./input";
export type { InputExpectation, InputRejectionCode, InputResult } from "./input";
export { ensurePersistedRng, persistedRng } from "./rng";
export type { ChoiceDecisionContext } from "./decision";
export {
  createInitialState,
  applyDelta,
  cloneState,
  hydrateState,
  defaultModules,
  isScriptCompleted,
  markScriptCompleted,
  resolveModules,
  resolveRunFn,
} from "./state";
export { makeScriptState, emptyVisualState } from "./types";
export {
  trainingPreset,
  TRAINING_NAMESPACE,
  createTrainingState,
  trainingRun,
  buildHubSnapshot,
  sleepHandler,
} from "./presets/training";
export { vnRun } from "./presets/vn/run";
export { step, peek } from "./step";
export {
  compareChoiceSearchAssessment,
  searchForChoice,
  searchForScript,
} from "./search";
export type {
  ChoiceSearchOptions,
  ChoiceSearchProgress,
  ChoiceSearchClosest,
  ChoiceSearchRequirement,
  ChoiceSearchResult,
  ChoiceSearchTarget,
  ScriptSearchTarget,
} from "./search";
export { runLoop } from "./runLoop";
export type { StepResult } from "./step";
export type {
  TraceEntry,
  LoopReason,
  LoopResult,
  BehaviorCycleDiagnostic,
  StallCycleStep,
  StallDiagnostic,
  InputSource,
  RunLoopOptions,
} from "./runLoop";
export {
  baselineModule,
  BASELINE_NAMESPACE,
  createBaselineState,
} from "./modules/baseline";
export {
  runtimeModule,
  RUNTIME_NAMESPACE,
  createRuntimeState,
} from "./modules/runtime";
export {
  drainNarrations,
  checkEndConditions,
  checkTriggers,
  applyActionResult,
  runScript,
  dispatchActivity,
  mutateState,
  enterMap,
  EnterMapError,
  buildMapHubSnapshot,
  collectMapActivities,
  giveItem,
  consumeItem,
  hasItem,
  getEquippedWeapon,
  getEquippedWeaponPower,
  getWeaponPower,
  equipWeapon,
  hasSkill,
  learnSkill,
  forgetSkill,
  fireHook,
  fireOnSessionStart,
  fireOnScriptStart,
  fireOnScriptComplete,
  fireOnScriptSelect,
  fireOnBeatBefore,
  fireOnBeatAfter,
  fireOnChoicePresented,
  fireOnChoiceResolved,
  fireOnLabelEnter,
  fireOnActionDispatch,
  fireOnActionComplete,
  fireOnStateMutated,
  fireOnHubBuild,
  fireOnEndConditionFire,
  fireOnNarrationDrain,
} from "./primitives";
export { END_LABEL } from "./types";
export type {
  Action,
  ActionContext,
  ActionHandler,
  ActionResult,
  ActivityForecast,
  ActivityForecastMetric,
  AiAuditConfig,
  AssetKind,
  AssetRefs,
  AssetRenderings,
  AssetSize,
  AssetSpec,
  TuiRenderPrefs,
  Beat,
  BaselineState,
  CharacterDef,
  CharacterSpawnRule,
  CharacterStatDef,
  CharacterState,
  ChoiceOption,
  ComposedState,
  Condition,
  EndConditionSpec,
  EnemyDef,
  FlagValue,
  Game,
  HubActivity,
  HubResourceGroup,
  HubResourceSnapshot,
  HubSnapshot,
  Input,
  ItemDef,
  MapConnection,
  MapDef,
  Module,
  Output,
  PresetContext,
  RenderedChoice,
  RunFunction,
  RuntimeState,
  Script,
  ScriptInfo,
  ScriptState,
  SkillDef,
  StatDef,
  StatSnapshot,
  StatThreshold,
  StateDelta,
  StateMutationSource,
  SwitchDef,
  Trigger,
  TriggerHandler,
  TrainingConfig,
  TrainingState,
  VariableDef,
  VariableValue,
  VisualState,
  WeaponDef,
  WeaponState,
} from "./types";
