export { Engine, ModuleContractError, buildPresetContext } from "./engine";
export { evaluateCondition, explainCondition } from "./condition";
export {
  activityDecisionContext,
  choiceDecisionContext,
  resolveChoiceInput,
} from "./decision";
export {
  classifyInput,
  expectedInputs,
  retargetAcceptedInputResult,
} from "./input";
export { validateOutput, OutputContractError } from "./output";
export type { InputExpectation, InputRejectionCode, InputResult } from "./input";
export { ensurePersistedRng, persistedRng, statefulRng } from "./rng";
export type { ActivityDecisionContext, ChoiceDecisionContext } from "./decision";
export type {
  ModuleHookContext,
  ModuleHookName,
  OwnedTrigger,
  TriggerFailureStage,
} from "./types";
export {
  createInitialState,
  applyDelta,
  cloneState,
  hydrateState,
  defaultModules,
  isScriptCompleted,
  markScriptCompleted,
  resolveModules,
  resolveRunFn,
  ModuleInitializationError,
} from "./state";
export type { InitialStateOptions } from "./state";
export { makeScriptState, emptyVisualState } from "./types";
export {
  trainingPreset,
  TRAINING_NAMESPACE,
  createTrainingState,
  trainingRun,
  buildHubSnapshot,
  sleepHandler,
} from "./presets/training";
export { vnRun } from "./presets/vn/run";
export { step, peek } from "./step";
export {
  compareChoiceSearchAssessment,
  searchForChoice,
  searchForScript,
} from "./search";
export { validateAiPublicIntent } from "./runLoop";
export type {
  ChoiceSearchOptions,
  ChoiceSearchProgress,
  ChoiceSearchClosest,
  ChoiceSearchCheckpoint,
  ChoiceSearchCheckpointNode,
  ChoiceSearchCheckpointTarget,
  ChoiceSearchFrontier,
  ChoiceSearchRequirement,
  ChoiceSearchResult,
  ChoiceSearchTarget,
  ScriptSearchTarget,
} from "./search";
export { runLoop } from "./runLoop";
export { scriptRevision } from "./scriptRevision";
export type { StepResult } from "./step";
export type {
  TraceEntry,
  LoopReason,
  LoopResult,
  LoopFailure,
  BehaviorCycleDiagnostic,
  StallCycleStep,
  StallDiagnostic,
  InputSource,
  RunLoopOptions,
} from "./runLoop";
export {
  baselineModule,
  BASELINE_NAMESPACE,
  createBaselineState,
} from "./modules/baseline";
export {
  runtimeModule,
  RUNTIME_NAMESPACE,
  createRuntimeState,
} from "./modules/runtime";
export {
  drainNarrations,
  checkEndConditions,
  checkTriggers,
  TriggerExecutionError,
  applyActionResult,
  runScript,
  dispatchActivity,
  mutateState,
  enterMap,
  EnterMapError,
  buildMapHubSnapshot,
  collectMapActivities,
  giveItem,
  consumeItem,
  hasItem,
  getEquippedWeapon,
  getEquippedWeaponPower,
  getWeaponPower,
  equipWeapon,
  hasSkill,
  learnSkill,
  forgetSkill,
  fireHook,
  ModuleHookExecutionError,
  fireOnSessionStart,
  fireOnScriptStart,
  fireOnScriptComplete,
  fireOnScriptSelect,
  fireOnBeatBefore,
  fireOnBeatAfter,
  fireOnChoicePresented,
  fireOnChoiceResolved,
  fireOnLabelEnter,
  fireOnActionDispatch,
  fireOnActionComplete,
  fireOnStateMutated,
  fireOnHubBuild,
  fireOnEndConditionFire,
  fireOnNarrationDrain,
} from "./primitives";
export { END_LABEL } from "./types";
export type {
  Action,
  ActionContext,
  ActionHandler,
  ActionResult,
  ActivityForecast,
  ActivityForecastMetric,
  AiAuditConfig,
  AiPersonaDecider,
  AiPersonaDecision,
  AiPersonaContext,
  AiPersonaDefinition,
  AssetKind,
  AssetRefs,
  AssetRenderings,
  AssetSize,
  AssetSpec,
  TuiRenderPrefs,
  Beat,
  BaselineState,
  CharacterDef,
  CharacterSpawnRule,
  CharacterStatDef,
  CharacterState,
  ChoiceOption,
  ComposedState,
  Condition,
  EndConditionSpec,
  EnemyDef,
  FlagValue,
  Game,
  HubActivity,
  HubObjectiveRequirement,
  HubObjectiveScope,
  HubObjectiveSnapshot,
  HubResourceGroup,
  HubResourceSnapshot,
  HubSnapshot,
  Input,
  ItemDef,
  MapConnection,
  MapDef,
  Module,
  ModuleInitializationContext,
  Output,
  PresetContext,
  RenderedChoice,
  RunFunction,
  RuntimeState,
  Script,
  ScriptInfo,
  ScriptState,
  SkillDef,
  StatDef,
  StatSnapshot,
  StatThreshold,
  StateDelta,
  StateMutationSource,
  SwitchDef,
  Trigger,
  TriggerHandler,
  TrainingConfig,
  TrainingState,
  VariableDef,
  VariableValue,
  VisualState,
  WeaponDef,
  WeaponState,
} from "./types";
